USE [expense-tracker];

DROP TABLE GROUPS;

CREATE TABLE GROUPS(UNIQUE_ID BIGINT IDENTITY(1,1) PRIMARY KEY, NAME NVARCHAR(50) NOT NULL, DESCRIPTION NVARCHAR(2000) NOT NULL,CREATED_DT DATETIME2 NOT NULL, CREATED_BY NVARCHAR(255) NOT NULL);

DROP TABLE USERS;

CREATE TABLE USERS(UNIQUE_ID BIGINT IDENTITY(1,1) PRIMARY KEY, NAME NVARCHAR(255) NOT NULL, MOBILE_NUMBER NVARCHAR(25) NOT NULL, EMAIL_ADDRESS NVARCHAR(255) NOT NULL);

DROP TABLE GROUP_USER_ASSIGNMENT;

CREATE table GROUP_USER_ASSIGNMENT(UNIQUE_ID BIGINT IDENTITY(1,1) PRIMARY KEY, GROUP_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL);

DROP TABLE USER_PAYMENT;

CREATE TABLE USER_PAYMENT(UNIQUE_ID BIGINT IDENTITY(1,1) PRIMARY KEY, EXP_DESC NVARCHAR(50) NOT NULL, PAYER BIGINT NOT NULL, AMOUNT NUMERIC(28,2) NOT NULL, GROUP_ID BIGINT NOT NULL, TYPE VARCHAR(1) NOT NULL, CREATED_DT DATETIME2 NOT NULL, UPDATED_DT DATETIME2 NOT NULL);

DROP TABLE PAYMENT_ALLOCATION;

CREATE TABLE PAYMENT_ALLOCATION(UNIQUE_ID BIGINT IDENTITY(1,1) PRIMARY KEY, TYPE_VAL NVARCHAR(50) NOT NULL, AMOUNT NUMERIC(28,2) NOT NULL, USER_PAYMENT_ID BIGINT NOT NULL);